name = "url-shortener"
compatibility_date = "2024-05-25"
pages_build_output_dir = ".svelte-kit/cloudflare"


kv_namespaces = [
    { binding = "LINKS", id = "$LINKS_KV_NAMESPACE_ID" },
    { binding = "HISTORY", id = "$HISTORY_KV_NAMESPACE_ID" },
]

[vars]
NODE_VERSION = "18.19.0"