name = "url-shortener"
compatibility_date = "2024-05-25"
pages_build_output_dir = ".svelte-kit/cloudflare"


kv_namespaces = [
    { binding = "LINKS", id = "b09a28dafdbc492d9e67eb60526b511c" },
    { binding = "HISTORY", id = "c533bcff20684107a665aa133131e11b" },
]

[vars]
NODE_VERSION = "18.19.0"